[package]
name = "derive_utils"
version = "0.11.2"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/derive_utils"
keywords = ["enum", "macros", "derive"]
categories = ["rust-patterns", "development-tools::procedural-macro-helpers"]
exclude = ["/.*", "/tools"]
description = """
A procedural macro helper for easily writing derive macros for enums.
"""

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[workspace]
members = ["examples/example", "examples/example_derive"]

# Note: proc-macro2, quote, and syn are public dependencies.
[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "1.0.56", features = ["full"] }

[dev-dependencies]
example_derive = { path = "examples/example_derive" }
rustversion = "1"
trybuild = "1"
