[package]
name = "derive_utils"
version = "0.9.1"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/derive_utils"
homepage = "https://github.com/taiki-e/derive_utils"
documentation = "https://docs.rs/derive_utils"
keywords = ["enum", "macros", "derive"]
categories = ["rust-patterns", "development-tools::procedural-macro-helpers"]
readme = "README.md"
description = """
A procedural macro helper for easily writing derive macros for enums.
"""

[workspace]
members = ["examples/example", "examples/example_derive"]

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
